---
title: 'Булыга А. М. ВКР: Типологические и ареальные аспекты адвербиальной редупликации
  в языках Дальнего Востока и Юго-Восточной Азии. Приложение 2. Интерактивные карты.'
output:  html_document
---

```{r}
library(lingtypology)
```

Список языков в нашем исследовании
```{r}
overalldf <- data.frame(language = c("Thai", "Maonan", "Lao", "Nung (Viet Nam)", "Hmong Daw", "Vietnamese", "Temiar", "Pacoh", "Chrau", "Koho", "Central Khmer", "Sô", "Shwe Palaung", "Pnar", "Min Nan Chinese", "Burmese", "Mandarin Chinese", "Cantonese", "Northern Tujia", "Kathmandu Valley Newari", "Lahu", "Lisu", "Tibetan", "Eastern Tamang", "Garo", "Southern Jinghpaw", "Camling", "Belhariya", "Northern Qiang", "Southern Pumi", "Eastern Kayah", "Phrae Pwo Karen", "Drung", "Southern Bai", "Bunun", "Tsou", "Puyuma", "Paiwan", "Kavalan", "Amis", "Atayal", "Ratahan", "Ibatan", "Yami", "Abenlen Ayta", "Pampanga", "Kankanaey", "Iloko", "Upper Tanudan Kalinga", "Central Bontoc", "Pangasinan", "Dupaninan Agta", "Tagalog", "Western Bukidnon Manobo", "Talaandig-Binukid", "Cebuano", "Hiligaynon", "Western Subanon", "Ibaloi", "Maguindanao", "Masbatenyo", "Tonsea", "Tondano", "Javanese", "Mualang", "Standard Indonesian", "Eastern Cham"), genetic = c("Tai-Kadai - Tai", "Tai-Kadai - Kam-Sui", "Tai-Kadai - Tai", "Tai-Kadai - Tai", "Hmong-Mien", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Austronesian - Formosan", "Austronesian - Formosan", "Austronesian - Formosan", "Austronesian - Formosan", "Austronesian - Formosan", "Austronesian - Formosan", "Austronesian - Formosan", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic"), advredupfix = c("yes", "yes", "yes", "no", "yes", "yes", "no", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "yes", "no", "no", "yes", "yes", "no", "yes", "no", "no", "no", "no", "no", "yes", "yes", "no", "yes", "yes", "yes", "no", "yes", "no", "yes", "yes", "yes", "yes", "no", "yes", "yes", "yes", "yes", "no", "yes", "yes", "no", "yes", "yes", "yes", "yes", "yes"))
overalldf
```

Распределение языков
```{r}
map.feature(languages = overalldf$language, features = overalldf$advredupfix, stroke.features = overalldf$genetic, title = "Is there adverbial reduplication?", stroke.title = "Genetic relation", color = c("white", "black"), stroke.color = "viridis")

```

Наречия образа действия
```{r}
advreddf_m <- data.frame(language = c("Thai", "Lao", "Maonan", "Hmong Daw", "Vietnamese", "Pacoh", "Chrau", "Koho", "Central Khmer", "Sô", "Shwe Palaung", "Pnar", "Min Nan Chinese", "Mandarin Chinese", "Cantonese", "Burmese", "Northern Tujia", "Garo", "Northern Qiang", "Phrae Pwo Karen", "Drung", "Bunun", "Atayal", "Ratahan", "Yami", "Abenlen Ayta", "Pampanga", "Iloko", "Central Bontoc", "Pangasinan", "Dupaninan Agta", "Tagalog", "Talaandig-Binukid", "Cebuano", "Hiligaynon", "Western Subanon", "Maguindanao", "Masbatenyo", "Tondano", "Javanese", "Mualang", "Standard Indonesian", "Eastern Cham"), genetic = c("Tai-Kadai - Tai", "Tai-Kadai - Tai", "Tai-Kadai - Kam-Sui", "Hmong-Mien", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Austronesian - Formosan", "Austronesian - Formosan", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic"), manneradv = c("yes", "no", "no", "no", "yes", "no", "yes", "yes", "no", "no", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "no", "no", "no", "no", "no", "yes", "no", "yes", "no", "no", "yes", "yes", "no", "yes", "yes", "yes", "no", "no", "yes", "yes", "yes", "yes"))
map.feature(languages = advreddf_m$language, features = advreddf_m$manneradv, stroke.features = advreddf_m$genetic, title = "Manner adverbs", stroke.title = "Genetic relation", color = c("white", "black"), stroke.color = "viridis")
```
Карта 2.

Наречия времени
```{r}
advreddf_t <- data.frame(language = c("Thai", "Lao", "Maonan", "Hmong Daw", "Vietnamese", "Pacoh", "Chrau", "Koho", "Central Khmer", "Sô", "Shwe Palaung", "Pnar", "Min Nan Chinese", "Mandarin Chinese", "Cantonese", "Burmese", "Northern Tujia", "Garo", "Northern Qiang", "Phrae Pwo Karen", "Drung", "Bunun", "Atayal", "Ratahan", "Yami", "Abenlen Ayta", "Pampanga", "Iloko", "Central Bontoc", "Pangasinan", "Dupaninan Agta", "Tagalog", "Talaandig-Binukid", "Cebuano", "Hiligaynon", "Western Subanon", "Maguindanao", "Masbatenyo", "Tondano", "Javanese", "Mualang", "Standard Indonesian", "Eastern Cham"), genetic = c("Tai-Kadai - Tai", "Tai-Kadai - Tai", "Tai-Kadai - Kam-Sui", "Hmong-Mien", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Austronesian - Formosan", "Austronesian - Formosan", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic"), tempadv = c("yes", "no", "yes", "no", "yes", "yes", "yes", "no", "no", "yes", "yes", "no", "yes", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "no", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "no", "yes"))
map.feature(languages = advreddf_t$language, features = advreddf_t$tempadv, stroke.features = advreddf_t$genetic, title = "Temporal adverbs", stroke.title = "Genetic relation", color = c("white", "black"), stroke.color = "viridis")
```

Наречия частотности
```{r}
advreddf_f <- data.frame(language = c("Thai", "Lao", "Maonan", "Hmong Daw", "Vietnamese", "Pacoh", "Chrau", "Koho", "Central Khmer", "Sô", "Shwe Palaung", "Pnar", "Min Nan Chinese", "Mandarin Chinese", "Cantonese", "Burmese", "Northern Tujia", "Garo", "Northern Qiang", "Phrae Pwo Karen", "Drung", "Bunun", "Atayal", "Ratahan", "Yami", "Abenlen Ayta", "Pampanga", "Iloko", "Central Bontoc", "Pangasinan", "Dupaninan Agta", "Tagalog", "Talaandig-Binukid", "Cebuano", "Hiligaynon", "Western Subanon", "Maguindanao", "Masbatenyo", "Tondano", "Javanese", "Mualang", "Standard Indonesian", "Eastern Cham"), genetic = c("Tai-Kadai - Tai", "Tai-Kadai - Tai", "Tai-Kadai - Kam-Sui", "Hmong-Mien", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Austronesian - Formosan", "Austronesian - Formosan", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic"), freqadv = c("yes", "no", "no", "no", "yes", "no", "no", "yes", "yes", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "yes", "no", "no", "no", "yes", "yes", "no", "yes", "yes", "no", "no", "no"))
map.feature(languages = advreddf_f$language, features = advreddf_f$freqadv, stroke.features = advreddf_f$genetic, title = "Frequency adverbs", stroke.title = "Genetic relation", color = c("white", "black"), stroke.color = "viridis")
```

Наречия места
```{r}
advreddf_s <- data.frame(language = c("Thai", "Lao", "Maonan", "Hmong Daw", "Vietnamese", "Pacoh", "Chrau", "Koho", "Central Khmer", "Sô", "Shwe Palaung", "Pnar", "Min Nan Chinese", "Mandarin Chinese", "Cantonese", "Burmese", "Northern Tujia", "Garo", "Northern Qiang", "Phrae Pwo Karen", "Drung", "Bunun", "Atayal", "Ratahan", "Yami", "Abenlen Ayta", "Pampanga", "Iloko", "Central Bontoc", "Pangasinan", "Dupaninan Agta", "Tagalog", "Talaandig-Binukid", "Cebuano", "Hiligaynon", "Western Subanon", "Maguindanao", "Masbatenyo", "Tondano", "Javanese", "Mualang", "Standard Indonesian", "Eastern Cham"), genetic = c("Tai-Kadai - Tai", "Tai-Kadai - Tai", "Tai-Kadai - Kam-Sui", "Hmong-Mien", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Austronesian - Formosan", "Austronesian - Formosan", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic"), spacadv = c("no", "yes", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "yes", "no", "no", "yes", "no", "no", "no"))
map.feature(languages = advreddf_s$language, features = advreddf_s$spacadv, stroke.features = advreddf_s$genetic, title = "Spacial adverbs", stroke.title = "Genetic relation", color = c("white", "black"), stroke.color = "viridis")
```

Наречия степени
```{r}
advreddf_d <- data.frame(language = c("Thai", "Lao", "Maonan", "Hmong Daw", "Vietnamese", "Pacoh", "Chrau", "Koho", "Central Khmer", "Sô", "Shwe Palaung", "Pnar", "Min Nan Chinese", "Mandarin Chinese", "Cantonese", "Burmese", "Northern Tujia", "Garo", "Northern Qiang", "Phrae Pwo Karen", "Drung", "Bunun", "Atayal", "Ratahan", "Yami", "Abenlen Ayta", "Pampanga", "Iloko", "Central Bontoc", "Pangasinan", "Dupaninan Agta", "Tagalog", "Talaandig-Binukid", "Cebuano", "Hiligaynon", "Western Subanon", "Maguindanao", "Masbatenyo", "Tondano", "Javanese", "Mualang", "Standard Indonesian", "Eastern Cham"), genetic = c("Tai-Kadai - Tai", "Tai-Kadai - Tai", "Tai-Kadai - Kam-Sui", "Hmong-Mien", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Austronesian - Formosan", "Austronesian - Formosan", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic"), degreeadv = c("no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "yes", "yes", "no")) 
map.feature(languages = advreddf_d$language, features = advreddf_d$degreeadv, stroke.features = advreddf_d$genetic, title = "Degree adverbs", stroke.title = "Genetic relation", color = c("white", "black"), stroke.color = "viridis")
```

Наречия субъективной модальности
```{r}
advreddf_sj <- data.frame(language = c("Thai", "Lao", "Maonan", "Hmong Daw", "Vietnamese", "Pacoh", "Chrau", "Koho", "Central Khmer", "Sô", "Shwe Palaung", "Pnar", "Min Nan Chinese", "Mandarin Chinese", "Cantonese", "Burmese", "Northern Tujia", "Garo", "Northern Qiang", "Phrae Pwo Karen", "Drung", "Bunun", "Atayal", "Ratahan", "Yami", "Abenlen Ayta", "Pampanga", "Iloko", "Central Bontoc", "Pangasinan", "Dupaninan Agta", "Tagalog", "Talaandig-Binukid", "Cebuano", "Hiligaynon", "Western Subanon", "Maguindanao", "Masbatenyo", "Tondano", "Javanese", "Mualang", "Standard Indonesian", "Eastern Cham"), genetic = c("Tai-Kadai - Tai", "Tai-Kadai - Tai", "Tai-Kadai - Kam-Sui", "Hmong-Mien", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Austroasiatic - Mon-Khmer", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Sinitic", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Sino-Tibetan - Tibeto-Burman", "Austronesian - Formosan", "Austronesian - Formosan", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Philippine", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic", "Austronesian - Malayo-Javanic"), subjadv = c("yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "yes", "no", "yes", "no", "no", "yes", "no"))
map.feature(languages = advreddf_sj$language, features = advreddf_sj$subjadv, stroke.features = advreddf_sj$genetic, title = "Subjective adverbs", stroke.title = "Genetic relation", color = c("white", "black"), stroke.color = "viridis")
```

Moroz G (2017). _lingtypology: easy mapping for Linguistic Typology_.
  <https://CRAN.R-project.org/package=lingtypology>.